/**
 * EV2 — fonts and icons served from our own origin (D71).
 *
 * The screens used to pull Tailwind, Font Awesome and Google Fonts from third-party
 * CDNs. The service worker only caches our own origin, so with a weak signal inside
 * the club the app opened without any styling. This script copies the exact font
 * files we use into `web/fonts/` and turns the icons we use into `css/src/icons.css`,
 * so everything the screens need is one same-origin stylesheet the worker can keep.
 *
 * Run through `npm run build:css`. The output is committed; CI checks it is current.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const WEB = path.join(__dirname, '..');
const NM = path.join(WEB, 'node_modules');

// ---- Fonts -------------------------------------------------------------------
const FONTS = {
  inter: [400, 500, 600, 700],
  poppins: [500, 600, 700],
};

const fontDir = path.join(WEB, 'fonts');
fs.mkdirSync(fontDir, { recursive: true });
for (const [family, weights] of Object.entries(FONTS)) {
  for (const w of weights) {
    const file = `${family}-latin-${w}-normal.woff2`;
    fs.copyFileSync(path.join(NM, '@fontsource', family, 'files', file), path.join(fontDir, file));
  }
  fs.copyFileSync(path.join(NM, '@fontsource', family, 'LICENSE'),
    path.join(fontDir, `LICENSE-${family}.txt`));
}

// ---- Icons -------------------------------------------------------------------
// Font Awesome Free (CC BY 4.0, https://fontawesome.com/license/free). Only the
// icons listed here ship. Markup keeps the familiar `fa-solid fa-<name>` classes.
const ICONS = {
  solid: [
    'arrow-left', 'arrow-right', 'arrow-right-from-bracket', 'bars', 'bell',
    'boxes-stacked', 'calendar-days', 'camera', 'car', 'cash-register', 'chart-line',
    'check', 'chevron-left', 'chevron-right', 'circle-check', 'clock', 'dolly', 'gear',
    'gift', 'hand-holding-dollar', 'heart', 'helmet-safety', 'house', 'inbox',
    'location-dot', 'magnifying-glass', 'map-location-dot', 'martini-glass', 'minus',
    'music', 'phone', 'plus', 'print', 'qrcode', 'receipt', 'right-from-bracket',
    'right-to-bracket', 'rotate', 'rotate-left', 'shield-halved', 'star', 'taxi',
    'triangle-exclamation', 'user', 'users', 'wallet', 'xmark',
  ],
  brands: ['apple', 'facebook-f', 'google', 'instagram'],
};

const svgDir = path.join(NM, '@fortawesome', 'fontawesome-free', 'svgs');
const lines = [
  '/* Generated by scripts/build-assets.js — do not edit by hand. */',
  '/* Icons: Font Awesome Free by @fontawesome — https://fontawesome.com, CC BY 4.0. */',
];
for (const [set, names] of Object.entries(ICONS)) {
  for (const name of names) {
    let svg = fs.readFileSync(path.join(svgDir, set, `${name}.svg`), 'utf8');
    svg = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/\s+/g, ' ').trim();
    const uri = `data:image/svg+xml,${encodeURIComponent(svg).replace(/'/g, '%27')}`;
    lines.push(`.fa-${name}{--fa-icon:url("${uri}")}`);
  }
}
fs.writeFileSync(path.join(WEB, 'css', 'src', 'icons.css'), `${lines.join('\n')}\n`);
console.log(`fonts: ${Object.values(FONTS).flat().length} files, icons: ${Object.values(ICONS).flat().length}`);
